config/routes.rb
Rails.application.routes.draw do
  root 'portal#index'

  resources :articles

  get 'signup', to: 'users#new'
  
  resources :users, except: [:new]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  

end

app/models/article.rb
class Article < ActiveRecord::Base
    belongs_to :user
    validates :title, presence: true, length: {minimum: 5, maximum: 50}
    validates :description, presence: true,  length: {minimum: 10, maximum: 300}
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :articles
    validates :username, presence: true,
    uniqueness: { case_sensitive: false },
    length: { minimum: 3, maximum: 25 }
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 105 },
    uniqueness: { case_sensitive: false },
    format: { with: VALID_EMAIL_REGEX }
has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !! current_user
  end
  
  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform this action"
      redirect_to root_path
    end
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  
  def index
    @articles = Article.paginate(page: params[:page], per_page: 6)
  end
      
  def show; end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(article_params)
    if @article.save
        flash[:success] = "Article was successfully created"
        redirect_to article_path(@article)
    else 
        render 'new'
    end
  end
      
  def edit; end
  
  def update
      if @article.update(article_params)
          flash[:success] = "Article was successfully updated"
          redirect_to article_path(@article)
      else
          render 'edit'
      end
  end
  
  def destroy
    @article.destroy
    flash[:danger] = "Article was successfully deleted"
    redirect_to articles_path
  end
  
  private 
  
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/portal_controller.rb
class PortalController < ApplicationController
  def index
    @articles = Article.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to user_path(user)
    else 
      flash.now[:danger] = "There is something wrong with your login information"
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show, :destroy]
  
  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 4)
  end
      
  def index
    @users = User.paginate(page: params[:page], per_page: 12)
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Ruby Project #{@user.username}"
      redirect_to 'index'
    else
      render 'new'
    end
  end
  
  def edit; end
  
  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to user_path
    else
      render 'edit'
    end
  end
  
  private 
  
  def set_user
    @user = User.find(params[:id])
  end
  
  def user_params
    params.require(:user).permit(:username, :email, :description, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = {size: 80})
        size = options[:size]
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "img-circle")
    end
    
    def cp(path)
        current_route = Rails.application.routes.recognize_path(path)
        "active" if current_page?(path)
    end
end

app/views/articles/_article.html.erb
<% obj.each do |a| %>
  <div class="col-centered post-card col-md-7">
    <%=link_to( image_tag('8.jpg'), article_path(a)) %>
    <h2><%= link_to "#{a.title}", article_path(a) %></h2>
    <p><%= truncate(a.description, length: 100) %></p>
    <div class="article-meta-details">
      <%= gravatar_for a.user, size: 25 %>
      <small><%= a.user.username %>, (<%= time_ago_in_words(a.created_at) %> ago)</small>
    </div>
    <% if logged_in? && current_user == a.user %>
      <p>
        <%= link_to 'Edit', edit_article_path(a), class: 'btn' %>
        <%= link_to 'Delete', article_path(a), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn' %>    
      </p>
    <% end %>
  </div>
<% end %>

app/views/articles/_articlesm.html.erb
<% obj.each do |a| %>
  <div class="col-md-4">
    <div class="post-card sm">
      <%=link_to( image_tag('8.jpg'), article_path(a)) %>
      <h1><%= link_to "#{a.title}", article_path(a) %></h1>
      <p><%= truncate(a.description, length: 100) %></p>
      <% if a.user %>
        <div class="article-meta-details">
            <%= link_to user_path(a.user) do %>
              <%= gravatar_for a.user, size: 25 %>
              <small><%= a.user.username %>, (<%= time_ago_in_words(a.created_at) %> ago)</small>
            <% end %>
        </div>
      <% end %>
      <p>
        <%= link_to 'Edit', edit_article_path(a), class: 'btn' %>
        <%= link_to 'Delete', article_path(a), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn' %>    
      </p>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= simple_form_for @article do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <div class="pull-right"><%= f.button :submit, class: 'btn btn-primary' %></div>
  <%= link_to "Cancel" , articles_path, class: 'btn' %>
<% end %>

app/views/articles/_info.html.erb
<h2><%= link_to "#{a.title}", article_path(a) %></h2>
<p><%= truncate(a.description, length: 100) %></p>
<div class="article-meta-details">
  <%= gravatar_for a.user, size: 25 %>
  <small><%= a.user.username %>, (<%= time_ago_in_words(a.created_at) %> ago)</small>
</div>
<p>
  <%= link_to 'Edit', edit_article_path(a), class: 'btn' %>
  <%= link_to 'Delete', article_path(a), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn' %>    
</p>

app/views/articles/edit.html.erb
<section class="page">
  <div class="container content">
    <div class="row col-sm-12">
      <h2>Article Edit Page</h2>
      <%= render partial: 'form' %>
    </div>
  </div>
</section>

app/views/articles/index.html.erb
<section class="articles-list">
  <div class="container">
    <div class="col-md-12">
      <h1 class="sitetitle">All articles</h1>
	    <p class="subtitle">
		    From our users crazy mind.
	    </p>
    </div>
    <%= render 'articlesm', obj: @articles %>
    <div class="col-md-12 text-center">
      <%= will_paginate %>
    </div>
  </div>
</section>

app/views/articles/new.html.erb
<section class="author-page">
  <div class="col-md-6 col-centered">
    <h2>New Article</h2>
    <%= render partial: 'form' %>
  </div>
</section>

app/views/articles/show.html.erb
<section class="article-page">
  <div class="col-md-8 col-centered">
    <%= link_to user_path(@article.user) do %>
      <div class="col-md-2 text-center"><%= gravatar_for @article.user, size: 90 %></div>
      <div class="col-md-10 align-left"><h1><%= @article.user.username %></h1></div>
    <% end %>
    <div class="col-md-10 align-left"><p><%= @article.user.description if @article.user.description %></p></div>
  </div>
  <div class="article-wrapper">
    <div class="col-centered col-md-7">
      <h1><%= @article.title %></h1>
      <%= image_tag("8.jpg") %>
      <p><%= @article.description %></p> 
      <%= link_to 'Back', articles_path, class: 'btn btn btn-primary' %>
      <% if logged_in? && current_user == @article.user %>
        <%= link_to 'Edit article', edit_article_path(@article), class: 'btn btn-primary' %>
        <%= link_to 'Delete article', article_path(@article), method: :delete, class: 'btn btn-danger' %>
      <% end %>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workspace</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>
  <body id="top">
    <%= render partial: "shared/navbar" %>
      <div class="msg-box col-sm-12"><%= render partial: "shared/messages" %></div>
      <%= yield %>
      <div class="col-md-12">
        <%= debug(params) if Rails.env.development? %>
      </div>
    </div>
    <!-- container -->
    <%= render partial: "shared/footer"%>
  </body>
</html>

app/views/portal/index.html.erb
<div class="container">
	<div class="mainheading col-md-12">
		<h1 class="sitetitle">What is your mind?</h1>
		<p class="subtitle">
			 Sign up and let the world know.
		</p>
	</div>

  <section class="featured-posts">
    <% @articles.each do |article| %>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <div class="card">
          <%= link_to article_path(article) do %>
            <div class="image-content col-md-6 col-xs-12">
              <div class="img-thumb"></div>
            </div>
            <div class="text-content col-md-6 col-xs-12">
              <h4><%= article.title %></h4>
              <p><%= article.description %></p>
            </div>
          <% end %>
          <div class="author-info col-md-6 col-xs-12">
            <div class="author-img-wrapper">
              <% if article.user %>
                <%= link_to user_path(article.user) do %>
                  <%= gravatar_for(article.user) %>
                  <small><%= article.user.username %></small>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </section>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title">
          <strong>
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this article from being saved:
          </strong>
        </h2>
        <div class="panel-body">
          <ul>
            <% obj.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>

 

app/views/shared/_footer.html.erb
<div class="footer col-md-12">
	<div class="container">
		<div class="col-md-12">
			<p class="pull-left">
				 Copyright &copy; 2017 B. Blog
			</p>
			<p class="pull-right">
				 Made with <%= link_to(image_tag("ruby_logo.png", class: 'footer-icon'), root_path) %> by <a target="_blank" href="https://www.bepelucio.com">Giulia Pizzignacco</a>
			</p>
		</div>
	</div>
</div>

app/views/shared/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class='alert alert-<%="#{name}" %>'>
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar custom-nav">
  <div class="container-fluid container">
    <div class="navbar-header col-md-2">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <div class="navbar-brand">
        <%= link_to 'B.', root_path %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Articles", articles_path, class: cp('/articles') %></li>
        <li><%= link_to "Users", users_path, class: cp('/users') %></li>
        <% if logged_in? %>
          <li class="user-dropdown">
            <span class="fa fa-user" data-toggle="dropdown"></span>
            <ul class="dropdown-menu">
              <li><%= link_to "View Profile", user_path(current_user) %></li>
              <li><%= link_to "Edit Account", edit_user_path(current_user) %></li>
              <li><%= link_to "Logout", logout_path, method: :delete, class: 'danger-text' %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign up", signup_path, class: cp('/signup') %></li>
          <li><%= link_to "Login", login_path, class: cp('/login') %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :username %>
  <%= f.input :description, as: :text %>
  <%= f.input :email %>
  <%= f.input :password %>
  <div class="pull-right"><%= f.submit(@user.new_record? ? "Sign up" : "Update your account", class: 'btn btn-primary') %></div>
<% end %>

app/views/users/edit.html.erb
<section class="edit-author-page">
    <div class="col-md-6 col-centered">
        <h1>Update my account</h1>
        <br/>
        <%= render 'form' %>
    </div>
</section>

app/views/users/index.html.erb
<section class="articles-list">
  <div class="container">
    <div class="col-md-12">
      <h1 class="sitetitle">Our brilliant minds</h1>
      <p class="subtitle">Sign up and join the club.</p>
    </div>
    <% @users.each do |user| %>
      <div class="col-md-3 text-center">
          <div class="author-card">
              <%= link_to gravatar_for(user), user_path(user) %>
              <h1><%= link_to user.username, user_path(user) %></h1>
              <h2><%= pluralize(user.articles.count, "article") if user.articles %></h2>
          </div>
      </div>
    <% end %>
    <div class="col-md-12 text-center">
      <%= will_paginate %>
    </div>
  </div>
</section>

app/views/users/new.html.erb
<section class="user-new">
  <div class="col-md-6 col-centered">
    <h3 class="text-center">New User</h3>
    <br/>
    <%= render 'form' %>
  </div>
</section>

app/views/users/show.html.erb
<section class="author-page">
  <div class="col-md-8 col-centered">
    <div class="col-md-2 text-center"><%= gravatar_for @user, size: 90 %></div>
    <div class="col-md-10 align-left"><h1><%= @user.username %></h1></div>
    <div class="col-md-10 align-left"><p><%= @user.description if @user.description %></p></div>
  </div>
  <div class="greybg">
    <%= render 'articles/article', obj: @user_articles  %>
    <div class="text-center">
        <%= will_paginate @user_articles %>
    </div>
  </div>
</section>